version: '3'

services:
  base: &base
    image: chatwoot/chatwoot:latest
    environment:
      - ACTIVE_STORAGE_SERVICE=${ACTIVE_STORAGE_SERVICE}
      - ANDROID_BUNDLE_ID=${ANDROID_BUNDLE_ID}
      - ANDROID_SHA256_CERT_FINGERPRINT=${ANDROID_SHA256_CERT_FINGERPRINT}
      - ASSET_CDN_HOST=${ASSET_CDN_HOST}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_REGION=${AWS_REGION}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AZURE_APP_ID=${AZURE_APP_ID}
      - AZURE_APP_SECRET=${AZURE_APP_SECRET}
      - DIRECT_UPLOADS_ENABLED=${DIRECT_UPLOADS_ENABLED}
      - ENABLE_ACCOUNT_SIGNUP=${ENABLE_ACCOUNT_SIGNUP}
      - ENABLE_PUSH_RELAY_SERVER=${ENABLE_PUSH_RELAY_SERVER}
      - FB_APP_ID=${FB_APP_ID}
      - FB_APP_SECRET=${FB_APP_SECRET}
      - FB_VERIFY_TOKEN=${FB_VERIFY_TOKEN}
      - FORCE_SSL=${FORCE_SSL}
      - FRONTEND_URL=${FRONTEND_URL}
      - GOOGLE_OAUTH_CALLBACK_URL=${GOOGLE_OAUTH_CALLBACK_URL}
      - GOOGLE_OAUTH_CLIENT_ID=${GOOGLE_OAUTH_CLIENT_ID}
      - GOOGLE_OAUTH_CLIENT_SECRET=${GOOGLE_OAUTH_CLIENT_SECRET}
      - IG_VERIFY_TOKEN=${IG_VERIFY_TOKEN}
      - IOS_APP_ID=${IOS_APP_ID}
      - LOG_LEVEL=${LOG_LEVEL}
      - LOG_SIZE=${LOG_SIZE}
      - MAILER_INBOUND_EMAIL_DOMAIN=${MAILER_INBOUND_EMAIL_DOMAIN}
      - MAILER_SENDER_EMAIL=${MAILER_SENDER_EMAIL}
      - MAILGUN_INGRESS_SIGNING_KEY=${MAILGUN_INGRESS_SIGNING_KEY}
      - MANDRILL_INGRESS_API_KEY=${MANDRILL_INGRESS_API_KEY}
      - POSTGRES_DATABASE=${POSTGRES_DATABASE}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USERNAME=${POSTGRES_USERNAME}
      - RAILS_ENV=${RAILS_ENV}
      - RAILS_INBOUND_EMAIL_PASSWORD=${RAILS_INBOUND_EMAIL_PASSWORD}
      - RAILS_INBOUND_EMAIL_SERVICE=${RAILS_INBOUND_EMAIL_SERVICE}
      - RAILS_LOG_TO_STDOUT=${RAILS_LOG_TO_STDOUT}
      - RAILS_MAX_THREADS=${RAILS_MAX_THREADS}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_SENTINELS=${REDIS_SENTINELS}
      - REDIS_SENTINEL_MASTER_NAME=${REDIS_SENTINEL_MASTER_NAME}
      - REDIS_URL=${REDIS_URL}
      - S3_BUCKET_NAME=${S3_BUCKET_NAME}
      - SECRET_KEY_BASE=${SECRET_KEY_BASE}
      - SENTIMENT_FILE_PATH=${SENTIMENT_FILE_PATH}
      - SLACK_CLIENT_ID=${SLACK_CLIENT_ID}
      - SLACK_CLIENT_SECRET=${SLACK_CLIENT_SECRET}
      - SMTP_ADDRESS=${SMTP_ADDRESS}
      - SMTP_AUTHENTICATION=${SMTP_AUTHENTICATION}
      - SMTP_DOMAIN=${SMTP_DOMAIN}
      - SMTP_ENABLE_STARTTLS_AUTO=${SMTP_ENABLE_STARTTLS_AUTO}
      - SMTP_OPENSSL_VERIFY_MODE=${SMTP_OPENSSL_VERIFY_MODE}
      - SMTP_PASSWORD=${SMTP_PASSWORD}
      - SMTP_PORT=${SMTP_PORT}
      - SMTP_USERNAME=${SMTP_USERNAME}
      - STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}
      - STRIPE_WEBHOOK_SECRET=${STRIPE_WEBHOOK_SECRET}
      - TWITTER_APP_ID=${TWITTER_APP_ID}
      - TWITTER_CONSUMER_KEY=${TWITTER_CONSUMER_KEY}
      - TWITTER_CONSUMER_SECRET=${TWITTER_CONSUMER_SECRET}
      - TWITTER_ENVIRONMENT=${TWITTER_ENVIRONMENT}
    volumes:
      - /data/storage:/app/storage

  rails:
    <<: *base
    depends_on:
      - postgres
      - redis
    ports:
      - '127.0.0.1:3000:3000'
    environment:
      - NODE_ENV=production
      - RAILS_ENV=production
      - INSTALLATION_ENV=docker
    entrypoint: docker/entrypoints/rails.sh
    command: ['bundle', 'exec', 'rails', 's', '-p', '3000', '-b', '0.0.0.0']

  sidekiq:
    <<: *base
    depends_on:
      - postgres
      - redis
    environment:
      - NODE_ENV=production
      - RAILS_ENV=production
      - INSTALLATION_ENV=docker
    command: ['bundle', 'exec', 'sidekiq', '-C', 'config/sidekiq.yml']

  postgres:
    image: postgres:12
    restart: always
    ports:
      - '127.0.0.1:5432:5432'
    volumes:
      - /data/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${POSTGRES_DATABASE}
      - POSTGRES_USER=${POSTGRES_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

  redis:
    image: redis:alpine
    restart: always
    command: ["sh", "-c", "redis-server --requirepass \"$REDIS_PASSWORD\""]
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_SENTINELS=${REDIS_SENTINELS}
      - REDIS_SENTINEL_MASTER_NAME=${REDIS_SENTINEL_MASTER_NAME}
      - REDIS_URL=${REDIS_URL}
    volumes:
      - /data/redis:/data
    ports:
      - '127.0.0.1:6379:6379'
